<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <AssemblyName>Pathoschild.Stardew.TestModAddedPath</AssemblyName>
    <RootNamespace>Pathoschild.Stardew.TestModAddedPath</RootNamespace>

    <TargetFramework>net6.0</TargetFramework>
    <LangVersion>latest</LangVersion>
  </PropertyGroup>

  <ItemGroup>
    <AdditionalFiles Include="$(SolutionDir)\shared_i18n\i18n\**\*" LinkBase="i18n" />
    <AdditionalFiles Include="$(MSBuildProjectDirectory)\added_paths\i18n\**\*" LinkBase="i18n" Link="i18n\%(RecursiveDir)\%(FileName)" />
  </ItemGroup>
</Project>
